ingress:
  enabled: true
  className: "nginx"
  host: "eoapi.tealwaters.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: eoapi-tls

serviceAccount:
  create: false
  name: "eoapi-workload-identity"

# Enable workload identity for all services
raster:
  settings:
    labels:
      azure.workload.identity/use: "true"
    envVars: 
      AZURE_STORAGE_ACCOUNT: "tealwaters"

browser:
  settings:
    labels:
      azure.workload.identity/use: "true"
    envVars: 
      AZURE_STORAGE_ACCOUNT: "tealwaters"

stac:
  settings:
    labels:
      azure.workload.identity/use: "true"
    envVars:
      AZURE_STORAGE_ACCOUNT: "tealwaters"
      STAC_FASTAPI_TITLE: "The TealWaters STAC Catalog"
      STAC_FASTAPI_DESCRIPTION: >
        The STAC endpoint is served at [https://eoapi.tealwaters.com/stac](https://eoapi.tealwaters.com/stac). This interface allows users to browser through our data products, including technical metadata and other relevant information.

vector:
  enabled: false

multidim:
  enabled: false
